"""update

Revision ID: 292fecb9e47a
Revises: b3f7ab390a8b
Create Date: 2025-01-23 17:19:02.467635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '292fecb9e47a'
down_revision = 'b3f7ab390a8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('a_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.drop_column('a_id')

    # ### end Alembic commands ###
